<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Manager;
use App\Models\Receptionist;
use App\Models\Trainer;
use App\Models\StaffLog;

class AdminStaffController extends Controller
{
    /**
     * Kirim email verifikasi dengan aman: kalau server email (SMTP) sedang
     * tidak terhubung, alur pembuatan akun TIDAK boleh gagal (500).
     * Kegagalan dicatat ke log dan dikembalikan sebagai false supaya
     * controller bisa memberi tahu admin untuk kirim ulang nanti.
     */
    private function sendVerificationEmailSafely(User $staff): bool
    {
        try {
            $staff->sendEmailVerificationNotification();
            return true;
        } catch (\Throwable $e) {
            report($e);
            return false;
        }
    }

    public function index()
    {
        $user = Auth::user();
        $tenant = $user->tenant;

        $staffs = User::where('tenant_id', $tenant->id)
            ->whereIn('role', ['manager', 'owner'])
            ->latest()
            ->get();

        return view('admin.staff.index', compact('staffs', 'tenant'));
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        if ($user->isOwner()) {
            return redirect()->back()->with('error', 'Mode Pemantauan Owner: Anda hanya memiliki hak akses untuk melihat data.');
        }
        $tenant = $user->tenant;

        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email',
            'password' => 'nullable|string|min:4',
            'role' => 'required|string',
            'phone' => 'nullable|string|max:20',
        ], [
            'name.required'  => 'Nama staf wajib diisi.',
            'email.required' => 'Email login wajib diisi.',
            'email.email'    => 'Format email tidak valid.',
            'email.unique'   => 'Email ini sudah terdaftar, gunakan email lain.',
            'password.min'   => 'Password minimal 4 karakter.',
            'role.required'  => 'Role / jabatan wajib dipilih.',
        ]);

        if ($tenant && !$tenant->canAddStaff()) {
            $maxStaff = $tenant->maxStaff();
            return redirect()->back()->with('error', "Gagal menambahkan akun staf: Kuota maksimal karyawan untuk {$tenant->plan_name} ({$maxStaff} Akun Karyawan) telah tercapai. Silakan lakukan upgrade paket.");
        }

        if ($tenant && !$tenant->isStaffRoleAllowed($request->role)) {
            return redirect()->back()->with('error', "Paket {$tenant->plan_name} dirancang untuk gym skala kecil dengan maksimal 5 akun staf (Staf & Resepsionis). Untuk mengelola akun Manager Gym & Personal Trainer, silakan upgrade ke Paket Pro atau Enterprise.");
        }

        if ($user->isAdmin() && !in_array($request->role, ['manager', 'owner', 'receptionist', 'supervisor'])) {
            return redirect()->back()->with('error', 'Admin hanya dapat mendaftarkan akun staf resmi gym.');
        }

        if ($user->isManager() && !in_array($request->role, ['receptionist', 'trainer', 'supervisor'])) {
            return redirect()->back()->with('error', 'Manager Gym hanya dapat mendaftarkan akun staf operasional (Resepsionis, Supervisor & Personal Trainer).');
        }

        // Jika password kosong → generate password default otomatis
        $autoGenerated = false;
        if (empty($request->password)) {
            $rawPassword = 'PetGym-' . strtoupper(substr(md5(uniqid(mt_rand(), true)), 0, 8));
            $autoGenerated = true;
        } else {
            $rawPassword = $request->password;
        }

        $staff = User::create([
            'tenant_id' => $tenant->id,
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($rawPassword),
            'role' => $request->role,
            'must_change_password' => true,
        ]);

        // Auto Sync ke tabel profil dedicated berdasarkan role
        if ($staff->role === 'manager') {
            Manager::updateOrCreate(
                ['tenant_id' => $tenant->id, 'user_id' => $staff->id],
                ['name' => $staff->name, 'email' => $staff->email, 'department' => 'Operasional', 'status' => 'active']
            );
        } elseif ($staff->role === 'receptionist') {
            Receptionist::updateOrCreate(
                ['tenant_id' => $tenant->id, 'user_id' => $staff->id],
                ['name' => $staff->name, 'email' => $staff->email, 'shift' => 'Pagi', 'status' => 'active']
            );
        } elseif ($staff->role === 'trainer') {
            Trainer::updateOrCreate(
                ['tenant_id' => $tenant->id, 'user_id' => $staff->id],
                ['name' => $staff->name, 'email' => $staff->email, 'phone' => $request->phone, 'specialization' => 'Fitness & Conditioning', 'status' => 'active']
            );
        }

        StaffLog::create([
            'tenant_id' => $tenant->id,
            'user_id' => $user->id,
            'action' => 'Tambah Akun Staf',
            'description' => "Mendaftarkan akun staf baru: {$staff->name} ({$staff->email}) sebagai {$staff->role}",
            'ip_address' => $request->ip(),
        ]);

        // Akun staf baru WAJIB verifikasi email dulu sebelum bisa login ke dashboard.
        // Kalau server email sedang mati, akun TETAP tersimpan — admin tinggal
        // pakai tombol "Kirim Verifikasi" nanti (email gagal TIDAK menggagalkan akun).
        $emailSent = $this->sendVerificationEmailSafely($staff);

        if (!$emailSent) {
            return redirect()->route('admin.staff.index')->with('warning', "Akun staf {$staff->name} berhasil dibuat, TETAPI email verifikasi gagal terkirim (server email tidak terhubung). Gunakan tombol 'Kirim Verifikasi' di daftar staf setelah server email aktif.");
        }

        return redirect()->route('admin.staff.index')->with('success', "Akun staf {$staff->name} berhasil dibuat. Link verifikasi email telah dikirim ke {$staff->email} — staf harus memverifikasi emailnya sebelum bisa login.");
    }

    /**
     * Mengirim ulang link verifikasi email untuk akun staf yang belum verifikasi.
     */
    public function sendVerification(Request $request, $id)
    {
        $user = Auth::user();
        $tenant = $user->tenant;

        $staff = User::where('tenant_id', $tenant->id)->findOrFail($id);

        if ($user->isAdmin() && !in_array($staff->role, ['manager', 'owner'])) {
            return redirect()->route('admin.staff.index')->with('error', 'Admin hanya dapat mengelola akun Manager Gym dan Owner.');
        }

        if ($user->isManager() && !in_array($staff->role, ['receptionist', 'trainer'])) {
            return redirect()->route('admin.staff.index')->with('error', 'Manager Gym hanya dapat mengelola akun Resepsionis dan Personal Trainer.');
        }

        if ($staff->hasVerifiedEmail()) {
            return redirect()->route('admin.staff.index')->with('success', "Email akun {$staff->name} sudah terverifikasi.");
        }

        $emailSent = $this->sendVerificationEmailSafely($staff);

        StaffLog::create([
            'tenant_id' => $tenant->id,
            'user_id' => $user->id,
            'action' => 'Kirim Ulang Verifikasi Email',
            'description' => "Mengirim ulang link verifikasi email untuk akun staf {$staff->name}",
            'ip_address' => $request->ip(),
        ]);

        if (!$emailSent) {
            return redirect()->route('admin.staff.index')->with('error', "Link verifikasi email GAGAL dikirim ke {$staff->email} (server email tidak terhubung). Coba lagi setelah server email aktif.");
        }

        return redirect()->route('admin.staff.index')->with('success', "Link verifikasi email telah dikirim ulang ke {$staff->email}.");
    }

    public function destroy(Request $request, $id)
    {
        $user = Auth::user();
        $tenant = $user->tenant;

        if ($user->id == $id) {
            return redirect()->route('admin.staff.index')->with('error', 'Anda tidak dapat menghapus akun Anda sendiri.');
        }

        $staff = User::where('tenant_id', $tenant->id)->findOrFail($id);
        
        if ($user->isAdmin() && !in_array($staff->role, ['manager', 'owner'])) {
            return redirect()->route('admin.staff.index')->with('error', 'Admin hanya dapat mengelola akun Manager Gym dan Owner.');
        }

        if ($user->isManager() && !in_array($staff->role, ['receptionist', 'trainer'])) {
            return redirect()->route('admin.staff.index')->with('error', 'Manager Gym hanya dapat mengelola akun Resepsionis dan Personal Trainer.');
        }

        $staffName = $staff->name;

        // Clean up role profile records
        Manager::where('user_id', $staff->id)->delete();
        Receptionist::where('user_id', $staff->id)->delete();
        Trainer::where('user_id', $staff->id)->delete();

        $staff->delete();

        StaffLog::create([
            'tenant_id' => $tenant->id,
            'user_id' => $user->id,
            'action' => 'Hapus Akun Staf',
            'description' => "Menghapus akun staf {$staffName}",
            'ip_address' => $request->ip(),
        ]);

        return redirect()->route('admin.staff.index')->with('success', "Akun staf {$staffName} berhasil dihapus.");
    }

    public function toggleStatus(Request $request, $id)
    {
        $user = Auth::user();
        if ($user->isOwner()) {
            return redirect()->back()->with('error', 'Mode Pemantauan Owner: Anda hanya memiliki hak akses untuk melihat data.');
        }
        $tenant = $user->tenant;

        if ($user->id == $id) {
            return redirect()->route('admin.staff.index')->with('error', 'Anda tidak dapat menonaktifkan akun Anda sendiri.');
        }

        $staff = User::where('tenant_id', $tenant->id)->findOrFail($id);

        if (!in_array($staff->role, ['manager', 'owner'])) {
            return redirect()->route('admin.staff.index')->with('error', 'Admin hanya dapat mengatur status akun Manager dan Owner.');
        }

        $newStatus = !$staff->isActive();
        $staff->update(['is_active' => $newStatus]);

        $statusText = $newStatus ? 'diaktifkan kembali' : 'dinonaktifkan';

        StaffLog::create([
            'tenant_id' => $tenant->id,
            'user_id' => $user->id,
            'action' => $newStatus ? 'Aktivasi Akun Staf' : 'Nonaktifkan Akun Staf',
            'description' => "Admin {$user->name} mengubah status akun {$staff->name} ({$staff->role}) menjadi {$statusText}.",
            'ip_address' => $request->ip(),
        ]);

        return redirect()->route('admin.staff.index')->with('success', "Akun {$staff->name} berhasil {$statusText}.");
    }
}